import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Open Me When",
  description: "Generated by create next app",
};

export default function OpenMeWhen({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main>{children}</main>;
}
